import type {GeologicPeriod, TimePoint} from './temporal-graph';
import {getTimeValue} from './temporal-graph';

/**
 * Comprehensive geologic time scale with full hierarchy: Eon → Era → Period → Epoch → Age
 * All times are in years ago.
 * Source: International Commission on Stratigraphy (2024)
 *
 * Hierarchy levels:
 * - Eon: Largest division (e.g., Phanerozoic, Proterozoic)
 * - Era: Major division within eon (e.g., Cenozoic, Mesozoic, Paleozoic)
 * - Period: Division within era (e.g., Quaternary, Cretaceous, Jurassic)
 * - Epoch: Division within period (e.g., Holocene, Pleistocene, Late Jurassic)
 * - Sub-Epoch: Division within epoch (where applicable)
 * - Age: Smallest standard division (e.g., Meghalayan, Calabrian)
 */

export const GEOLOGIC_PERIODS: GeologicPeriod[] = [
  // ========== PHANEROZOIC EON ==========

  // --- CENOZOIC ERA ---

  // Quaternary Period
  {
    name: 'Meghalayan',
    start: 0,
    end: 4_200,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Cenozoic',
    period: 'Quaternary',
    epoch: 'Holocene',
    subEpoch: 'Late Holocene',
    color: '#FEF2CC',
  },
  {
    name: 'Northgrippian',
    start: 4_200,
    end: 8_200,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Cenozoic',
    period: 'Quaternary',
    epoch: 'Holocene',
    subEpoch: 'Middle Holocene',
    color: '#FEF2D5',
  },
  {
    name: 'Greenlandian',
    start: 8_200,
    end: 11_700,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Cenozoic',
    period: 'Quaternary',
    epoch: 'Holocene',
    subEpoch: 'Early Holocene',
    color: '#FEF2E0',
  },
  {
    name: 'Holocene',
    start: 0,
    end: 11_700,
    level: 'epoch',
    eon: 'Phanerozoic',
    era: 'Cenozoic',
    period: 'Quaternary',
    color: '#FEF2E0',
  },
  {
    name: 'Late Pleistocene',
    start: 11_700,
    end: 129_000,
    level: 'sub-epoch',
    eon: 'Phanerozoic',
    era: 'Cenozoic',
    period: 'Quaternary',
    epoch: 'Pleistocene',
    color: '#FFF4AD',
  },
  {
    name: 'Chibanian',
    start: 129_000,
    end: 774_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Cenozoic',
    period: 'Quaternary',
    epoch: 'Pleistocene',
    subEpoch: 'Middle Pleistocene',
    color: '#FFF1A3',
  },
  {
    name: 'Calabrian',
    start: 774_000,
    end: 1_800_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Cenozoic',
    period: 'Quaternary',
    epoch: 'Pleistocene',
    subEpoch: 'Early Pleistocene',
    color: '#FFEE99',
  },
  {
    name: 'Gelasian',
    start: 1_800_000,
    end: 2_580_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Cenozoic',
    period: 'Quaternary',
    epoch: 'Pleistocene',
    subEpoch: 'Early Pleistocene',
    color: '#FFEB8F',
  },
  {
    name: 'Pleistocene',
    start: 11_700,
    end: 2_580_000,
    level: 'epoch',
    eon: 'Phanerozoic',
    era: 'Cenozoic',
    period: 'Quaternary',
    color: '#FFF2AE',
  },
  {
    name: 'Quaternary',
    start: 0,
    end: 2_580_000,
    level: 'period',
    eon: 'Phanerozoic',
    era: 'Cenozoic',
    color: '#FEF2E0',
  },

  // Neogene Period
  {
    name: 'Piacenzian',
    start: 2_580_000,
    end: 3_600_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Cenozoic',
    period: 'Neogene',
    epoch: 'Pliocene',
    subEpoch: 'Late Pliocene',
    color: '#FFFAD6',
  },
  {
    name: 'Zanclean',
    start: 3_600_000,
    end: 5_333_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Cenozoic',
    period: 'Neogene',
    epoch: 'Pliocene',
    subEpoch: 'Early Pliocene',
    color: '#FFFACD',
  },
  {
    name: 'Pliocene',
    start: 2_580_000,
    end: 5_333_000,
    level: 'epoch',
    eon: 'Phanerozoic',
    era: 'Cenozoic',
    period: 'Neogene',
    color: '#FFFACD',
  },
  {
    name: 'Messinian',
    start: 5_333_000,
    end: 7_246_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Cenozoic',
    period: 'Neogene',
    epoch: 'Miocene',
    subEpoch: 'Late Miocene',
    color: '#FFFF99',
  },
  {
    name: 'Tortonian',
    start: 7_246_000,
    end: 11_630_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Cenozoic',
    period: 'Neogene',
    epoch: 'Miocene',
    subEpoch: 'Late Miocene',
    color: '#FFFF8F',
  },
  {
    name: 'Serravallian',
    start: 11_630_000,
    end: 13_820_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Cenozoic',
    period: 'Neogene',
    epoch: 'Miocene',
    subEpoch: 'Middle Miocene',
    color: '#FFFF85',
  },
  {
    name: 'Langhian',
    start: 13_820_000,
    end: 15_970_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Cenozoic',
    period: 'Neogene',
    epoch: 'Miocene',
    subEpoch: 'Middle Miocene',
    color: '#FFFF7A',
  },
  {
    name: 'Burdigalian',
    start: 15_970_000,
    end: 20_440_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Cenozoic',
    period: 'Neogene',
    epoch: 'Miocene',
    subEpoch: 'Early Miocene',
    color: '#FFFF70',
  },
  {
    name: 'Aquitanian',
    start: 20_440_000,
    end: 23_030_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Cenozoic',
    period: 'Neogene',
    epoch: 'Miocene',
    subEpoch: 'Early Miocene',
    color: '#FFFF66',
  },
  {
    name: 'Miocene',
    start: 5_333_000,
    end: 23_030_000,
    level: 'epoch',
    eon: 'Phanerozoic',
    era: 'Cenozoic',
    period: 'Neogene',
    color: '#FFFF99',
  },
  {
    name: 'Neogene',
    start: 2_580_000,
    end: 23_030_000,
    level: 'period',
    eon: 'Phanerozoic',
    era: 'Cenozoic',
    color: '#FFFF00',
  },

  // Paleogene Period
  {
    name: 'Chattian',
    start: 23_030_000,
    end: 27_820_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Cenozoic',
    period: 'Paleogene',
    epoch: 'Oligocene',
    subEpoch: 'Late Oligocene',
    color: '#FED99A',
  },
  {
    name: 'Rupelian',
    start: 27_820_000,
    end: 33_900_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Cenozoic',
    period: 'Paleogene',
    epoch: 'Oligocene',
    subEpoch: 'Early Oligocene',
    color: '#FED28A',
  },
  {
    name: 'Oligocene',
    start: 23_030_000,
    end: 33_900_000,
    level: 'epoch',
    eon: 'Phanerozoic',
    era: 'Cenozoic',
    period: 'Paleogene',
    color: '#FED99A',
  },
  {
    name: 'Priabonian',
    start: 33_900_000,
    end: 37_800_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Cenozoic',
    period: 'Paleogene',
    epoch: 'Eocene',
    subEpoch: 'Late Eocene',
    color: '#FDC07A',
  },
  {
    name: 'Bartonian',
    start: 37_800_000,
    end: 41_200_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Cenozoic',
    period: 'Paleogene',
    epoch: 'Eocene',
    subEpoch: 'Middle Eocene',
    color: '#FDB96A',
  },
  {
    name: 'Lutetian',
    start: 41_200_000,
    end: 47_800_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Cenozoic',
    period: 'Paleogene',
    epoch: 'Eocene',
    subEpoch: 'Middle Eocene',
    color: '#FDB25A',
  },
  {
    name: 'Ypresian',
    start: 47_800_000,
    end: 56_000_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Cenozoic',
    period: 'Paleogene',
    epoch: 'Eocene',
    subEpoch: 'Early Eocene',
    color: '#FDAB4A',
  },
  {
    name: 'Eocene',
    start: 33_900_000,
    end: 56_000_000,
    level: 'epoch',
    eon: 'Phanerozoic',
    era: 'Cenozoic',
    period: 'Paleogene',
    color: '#FDC07A',
  },
  {
    name: 'Thanetian',
    start: 56_000_000,
    end: 59_200_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Cenozoic',
    period: 'Paleogene',
    epoch: 'Paleocene',
    subEpoch: 'Late Paleocene',
    color: '#FDA75F',
  },
  {
    name: 'Selandian',
    start: 59_200_000,
    end: 61_600_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Cenozoic',
    period: 'Paleogene',
    epoch: 'Paleocene',
    subEpoch: 'Middle Paleocene',
    color: '#FDA04F',
  },
  {
    name: 'Danian',
    start: 61_600_000,
    end: 66_000_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Cenozoic',
    period: 'Paleogene',
    epoch: 'Paleocene',
    subEpoch: 'Early Paleocene',
    color: '#FD993F',
  },
  {
    name: 'Paleocene',
    start: 56_000_000,
    end: 66_000_000,
    level: 'epoch',
    eon: 'Phanerozoic',
    era: 'Cenozoic',
    period: 'Paleogene',
    color: '#FDA75F',
  },
  {
    name: 'Paleogene',
    start: 23_030_000,
    end: 66_000_000,
    level: 'period',
    eon: 'Phanerozoic',
    era: 'Cenozoic',
    color: '#FD9A52',
  },
  {
    name: 'Cenozoic',
    start: 0,
    end: 66_000_000,
    level: 'era',
    eon: 'Phanerozoic',
    color: '#F2F91D',
  },

  // --- MESOZOIC ERA ---

  // Cretaceous Period
  {
    name: 'Maastrichtian',
    start: 66_000_000,
    end: 72_100_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Mesozoic',
    period: 'Cretaceous',
    epoch: 'Late Cretaceous',
    color: '#8CFF74',
  },
  {
    name: 'Campanian',
    start: 72_100_000,
    end: 83_600_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Mesozoic',
    period: 'Cretaceous',
    epoch: 'Late Cretaceous',
    color: '#7FFA66',
  },
  {
    name: 'Santonian',
    start: 83_600_000,
    end: 86_300_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Mesozoic',
    period: 'Cretaceous',
    epoch: 'Late Cretaceous',
    color: '#73F758',
  },
  {
    name: 'Coniacian',
    start: 86_300_000,
    end: 89_800_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Mesozoic',
    period: 'Cretaceous',
    epoch: 'Late Cretaceous',
    color: '#66F04A',
  },
  {
    name: 'Turonian',
    start: 89_800_000,
    end: 93_900_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Mesozoic',
    period: 'Cretaceous',
    epoch: 'Late Cretaceous',
    color: '#59E63C',
  },
  {
    name: 'Cenomanian',
    start: 93_900_000,
    end: 100_500_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Mesozoic',
    period: 'Cretaceous',
    epoch: 'Late Cretaceous',
    color: '#4CDB2E',
  },
  {
    name: 'Late Cretaceous',
    start: 66_000_000,
    end: 100_500_000,
    level: 'epoch',
    eon: 'Phanerozoic',
    era: 'Mesozoic',
    period: 'Cretaceous',
    color: '#8CFF74',
  },
  {
    name: 'Albian',
    start: 100_500_000,
    end: 113_000_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Mesozoic',
    period: 'Cretaceous',
    epoch: 'Early Cretaceous',
    color: '#B3FF9E',
  },
  {
    name: 'Aptian',
    start: 113_000_000,
    end: 121_400_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Mesozoic',
    period: 'Cretaceous',
    epoch: 'Early Cretaceous',
    color: '#A6FA91',
  },
  {
    name: 'Barremian',
    start: 121_400_000,
    end: 125_770_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Mesozoic',
    period: 'Cretaceous',
    epoch: 'Early Cretaceous',
    color: '#99F584',
  },
  {
    name: 'Hauterivian',
    start: 125_770_000,
    end: 132_600_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Mesozoic',
    period: 'Cretaceous',
    epoch: 'Early Cretaceous',
    color: '#8CF077',
  },
  {
    name: 'Valanginian',
    start: 132_600_000,
    end: 139_800_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Mesozoic',
    period: 'Cretaceous',
    epoch: 'Early Cretaceous',
    color: '#7FEB6A',
  },
  {
    name: 'Berriasian',
    start: 139_800_000,
    end: 145_000_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Mesozoic',
    period: 'Cretaceous',
    epoch: 'Early Cretaceous',
    color: '#73E65D',
  },
  {
    name: 'Early Cretaceous',
    start: 100_500_000,
    end: 145_000_000,
    level: 'epoch',
    eon: 'Phanerozoic',
    era: 'Mesozoic',
    period: 'Cretaceous',
    color: '#7EE56C',
  },
  {
    name: 'Cretaceous',
    start: 66_000_000,
    end: 145_000_000,
    level: 'period',
    eon: 'Phanerozoic',
    era: 'Mesozoic',
    color: '#7FC64E',
  },

  // Jurassic Period
  {
    name: 'Tithonian',
    start: 145_000_000,
    end: 152_100_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Mesozoic',
    period: 'Jurassic',
    epoch: 'Late Jurassic',
    color: '#73D2BA',
  },
  {
    name: 'Kimmeridgian',
    start: 152_100_000,
    end: 157_300_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Mesozoic',
    period: 'Jurassic',
    epoch: 'Late Jurassic',
    color: '#66CDAD',
  },
  {
    name: 'Oxfordian',
    start: 157_300_000,
    end: 163_500_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Mesozoic',
    period: 'Jurassic',
    epoch: 'Late Jurassic',
    color: '#59C8A0',
  },
  {
    name: 'Late Jurassic',
    start: 145_000_000,
    end: 163_500_000,
    level: 'epoch',
    eon: 'Phanerozoic',
    era: 'Mesozoic',
    period: 'Jurassic',
    color: '#67CCBA',
  },
  {
    name: 'Callovian',
    start: 163_500_000,
    end: 166_100_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Mesozoic',
    period: 'Jurassic',
    epoch: 'Middle Jurassic',
    color: '#59C1B3',
  },
  {
    name: 'Bathonian',
    start: 166_100_000,
    end: 168_300_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Mesozoic',
    period: 'Jurassic',
    epoch: 'Middle Jurassic',
    color: '#4CBAA6',
  },
  {
    name: 'Bajocian',
    start: 168_300_000,
    end: 170_300_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Mesozoic',
    period: 'Jurassic',
    epoch: 'Middle Jurassic',
    color: '#3FB399',
  },
  {
    name: 'Aalenian',
    start: 170_300_000,
    end: 174_100_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Mesozoic',
    period: 'Jurassic',
    epoch: 'Middle Jurassic',
    color: '#32AC8C',
  },
  {
    name: 'Middle Jurassic',
    start: 163_500_000,
    end: 174_100_000,
    level: 'epoch',
    eon: 'Phanerozoic',
    era: 'Mesozoic',
    period: 'Jurassic',
    color: '#4DB8AD',
  },
  {
    name: 'Toarcian',
    start: 174_100_000,
    end: 182_700_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Mesozoic',
    period: 'Jurassic',
    epoch: 'Early Jurassic',
    color: '#40ADA0',
  },
  {
    name: 'Pliensbachian',
    start: 182_700_000,
    end: 190_800_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Mesozoic',
    period: 'Jurassic',
    epoch: 'Early Jurassic',
    color: '#33A693',
  },
  {
    name: 'Sinemurian',
    start: 190_800_000,
    end: 199_300_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Mesozoic',
    period: 'Jurassic',
    epoch: 'Early Jurassic',
    color: '#269F86',
  },
  {
    name: 'Hettangian',
    start: 199_300_000,
    end: 201_300_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Mesozoic',
    period: 'Jurassic',
    epoch: 'Early Jurassic',
    color: '#199879',
  },
  {
    name: 'Early Jurassic',
    start: 174_100_000,
    end: 201_300_000,
    level: 'epoch',
    eon: 'Phanerozoic',
    era: 'Mesozoic',
    period: 'Jurassic',
    color: '#33A3A0',
  },
  {
    name: 'Jurassic',
    start: 145_000_000,
    end: 201_300_000,
    level: 'period',
    eon: 'Phanerozoic',
    era: 'Mesozoic',
    color: '#34B2C9',
  },

  // Triassic Period
  {
    name: 'Rhaetian',
    start: 201_300_000,
    end: 208_500_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Mesozoic',
    period: 'Triassic',
    epoch: 'Late Triassic',
    color: '#B28CFF',
  },
  {
    name: 'Norian',
    start: 208_500_000,
    end: 227_000_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Mesozoic',
    period: 'Triassic',
    epoch: 'Late Triassic',
    color: '#A87FF2',
  },
  {
    name: 'Carnian',
    start: 227_000_000,
    end: 237_000_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Mesozoic',
    period: 'Triassic',
    epoch: 'Late Triassic',
    color: '#9E73E5',
  },
  {
    name: 'Late Triassic',
    start: 201_300_000,
    end: 237_000_000,
    level: 'epoch',
    eon: 'Phanerozoic',
    era: 'Mesozoic',
    period: 'Triassic',
    color: '#B28CFF',
  },
  {
    name: 'Ladinian',
    start: 237_000_000,
    end: 242_000_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Mesozoic',
    period: 'Triassic',
    epoch: 'Middle Triassic',
    color: '#A67FEB',
  },
  {
    name: 'Anisian',
    start: 242_000_000,
    end: 247_200_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Mesozoic',
    period: 'Triassic',
    epoch: 'Middle Triassic',
    color: '#9C70D8',
  },
  {
    name: 'Middle Triassic',
    start: 237_000_000,
    end: 247_200_000,
    level: 'epoch',
    eon: 'Phanerozoic',
    era: 'Mesozoic',
    period: 'Triassic',
    color: '#9E70E5',
  },
  {
    name: 'Olenekian',
    start: 247_200_000,
    end: 251_200_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Mesozoic',
    period: 'Triassic',
    epoch: 'Early Triassic',
    color: '#9266D1',
  },
  {
    name: 'Induan',
    start: 251_200_000,
    end: 251_900_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Mesozoic',
    period: 'Triassic',
    epoch: 'Early Triassic',
    color: '#8A5DC7',
  },
  {
    name: 'Early Triassic',
    start: 247_200_000,
    end: 251_900_000,
    level: 'epoch',
    eon: 'Phanerozoic',
    era: 'Mesozoic',
    period: 'Triassic',
    color: '#8A54CC',
  },
  {
    name: 'Triassic',
    start: 201_300_000,
    end: 251_900_000,
    level: 'period',
    eon: 'Phanerozoic',
    era: 'Mesozoic',
    color: '#983999',
  },
  {
    name: 'Mesozoic',
    start: 66_000_000,
    end: 251_900_000,
    level: 'era',
    eon: 'Phanerozoic',
    color: '#67C5CA',
  },

  // --- PALEOZOIC ERA ---

  {
    name: 'Changhsingian',
    start: 251_900_000,
    end: 254_140_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Paleozoic',
    period: 'Permian',
    epoch: 'Lopingian',
    color: '#F04028',
  },
  {
    name: 'Wuchiapingian',
    start: 254_140_000,
    end: 259_100_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Paleozoic',
    period: 'Permian',
    epoch: 'Lopingian',
    color: '#E8371B',
  },
  {
    name: 'Lopingian',
    start: 251_900_000,
    end: 259_100_000,
    level: 'epoch',
    eon: 'Phanerozoic',
    era: 'Paleozoic',
    period: 'Permian',
    color: '#F04028',
  },
  {
    name: 'Capitanian',
    start: 259_100_000,
    end: 265_100_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Paleozoic',
    period: 'Permian',
    epoch: 'Guadalupian',
    color: '#E0331E',
  },
  {
    name: 'Wordian',
    start: 265_100_000,
    end: 268_800_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Paleozoic',
    period: 'Permian',
    epoch: 'Guadalupian',
    color: '#D82F16',
  },
  {
    name: 'Roadian',
    start: 268_800_000,
    end: 273_010_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Paleozoic',
    period: 'Permian',
    epoch: 'Guadalupian',
    color: '#D02B0E',
  },
  {
    name: 'Guadalupian',
    start: 259_100_000,
    end: 273_010_000,
    level: 'epoch',
    eon: 'Phanerozoic',
    era: 'Paleozoic',
    period: 'Permian',
    color: '#E0331E',
  },
  {
    name: 'Kungurian',
    start: 273_010_000,
    end: 283_500_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Paleozoic',
    period: 'Permian',
    epoch: 'Cisuralian',
    color: '#C82706',
  },
  {
    name: 'Artinskian',
    start: 283_500_000,
    end: 290_100_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Paleozoic',
    period: 'Permian',
    epoch: 'Cisuralian',
    color: '#C02300',
  },
  {
    name: 'Sakmarian',
    start: 290_100_000,
    end: 293_520_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Paleozoic',
    period: 'Permian',
    epoch: 'Cisuralian',
    color: '#B81F00',
  },
  {
    name: 'Asselian',
    start: 293_520_000,
    end: 298_900_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Paleozoic',
    period: 'Permian',
    epoch: 'Cisuralian',
    color: '#B01B00',
  },
  {
    name: 'Cisuralian',
    start: 273_010_000,
    end: 298_900_000,
    level: 'epoch',
    eon: 'Phanerozoic',
    era: 'Paleozoic',
    period: 'Permian',
    color: '#C82706',
  },
  {
    name: 'Permian',
    start: 251_900_000,
    end: 298_900_000,
    level: 'period',
    eon: 'Phanerozoic',
    era: 'Paleozoic',
    color: '#F04028',
  },
  {
    name: 'Pennsylvanian',
    start: 298_900_000,
    end: 323_200_000,
    level: 'sub-epoch',
    eon: 'Phanerozoic',
    era: 'Paleozoic',
    period: 'Carboniferous',
    color: '#67A599',
  },
  {
    name: 'Mississippian',
    start: 323_200_000,
    end: 358_900_000,
    level: 'sub-epoch',
    eon: 'Phanerozoic',
    era: 'Paleozoic',
    period: 'Carboniferous',
    color: '#5A998F',
  },
  {
    name: 'Carboniferous',
    start: 298_900_000,
    end: 358_900_000,
    level: 'period',
    eon: 'Phanerozoic',
    era: 'Paleozoic',
    color: '#67A599',
  },
  {
    name: 'Famennian',
    start: 358_900_000,
    end: 372_200_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Paleozoic',
    period: 'Devonian',
    epoch: 'Late Devonian',
    color: '#CB8C37',
  },
  {
    name: 'Frasnian',
    start: 372_200_000,
    end: 382_700_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Paleozoic',
    period: 'Devonian',
    epoch: 'Late Devonian',
    color: '#C3802A',
  },
  {
    name: 'Late Devonian',
    start: 358_900_000,
    end: 382_700_000,
    level: 'epoch',
    eon: 'Phanerozoic',
    era: 'Paleozoic',
    period: 'Devonian',
    color: '#CB8C37',
  },
  {
    name: 'Givetian',
    start: 382_700_000,
    end: 387_700_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Paleozoic',
    period: 'Devonian',
    epoch: 'Middle Devonian',
    color: '#BB741D',
  },
  {
    name: 'Eifelian',
    start: 387_700_000,
    end: 393_300_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Paleozoic',
    period: 'Devonian',
    epoch: 'Middle Devonian',
    color: '#B36810',
  },
  {
    name: 'Middle Devonian',
    start: 382_700_000,
    end: 393_300_000,
    level: 'epoch',
    eon: 'Phanerozoic',
    era: 'Paleozoic',
    period: 'Devonian',
    color: '#BB741D',
  },
  {
    name: 'Emsian',
    start: 393_300_000,
    end: 407_600_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Paleozoic',
    period: 'Devonian',
    epoch: 'Early Devonian',
    color: '#AB5C03',
  },
  {
    name: 'Pragian',
    start: 407_600_000,
    end: 410_800_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Paleozoic',
    period: 'Devonian',
    epoch: 'Early Devonian',
    color: '#A35000',
  },
  {
    name: 'Lochkovian',
    start: 410_800_000,
    end: 419_200_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Paleozoic',
    period: 'Devonian',
    epoch: 'Early Devonian',
    color: '#9B4400',
  },
  {
    name: 'Early Devonian',
    start: 393_300_000,
    end: 419_200_000,
    level: 'epoch',
    eon: 'Phanerozoic',
    era: 'Paleozoic',
    period: 'Devonian',
    color: '#AB5C03',
  },
  {
    name: 'Devonian',
    start: 358_900_000,
    end: 419_200_000,
    level: 'period',
    eon: 'Phanerozoic',
    era: 'Paleozoic',
    color: '#CB8C37',
  },
  {
    name: 'Pridoli',
    start: 419_200_000,
    end: 423_000_000,
    level: 'epoch',
    eon: 'Phanerozoic',
    era: 'Paleozoic',
    period: 'Silurian',
    color: '#B3E1B6',
  },
  {
    name: 'Ludlow',
    start: 423_000_000,
    end: 427_400_000,
    level: 'epoch',
    eon: 'Phanerozoic',
    era: 'Paleozoic',
    period: 'Silurian',
    color: '#A6DDA9',
  },
  {
    name: 'Wenlock',
    start: 427_400_000,
    end: 433_400_000,
    level: 'epoch',
    eon: 'Phanerozoic',
    era: 'Paleozoic',
    period: 'Silurian',
    color: '#99D99C',
  },
  {
    name: 'Llandovery',
    start: 433_400_000,
    end: 443_800_000,
    level: 'epoch',
    eon: 'Phanerozoic',
    era: 'Paleozoic',
    period: 'Silurian',
    color: '#8CD58F',
  },
  {
    name: 'Silurian',
    start: 419_200_000,
    end: 443_800_000,
    level: 'period',
    eon: 'Phanerozoic',
    era: 'Paleozoic',
    color: '#B3E1B6',
  },
  {
    name: 'Hirnantian',
    start: 443_800_000,
    end: 445_200_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Paleozoic',
    period: 'Ordovician',
    epoch: 'Late Ordovician',
    color: '#009270',
  },
  {
    name: 'Katian',
    start: 445_200_000,
    end: 453_000_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Paleozoic',
    period: 'Ordovician',
    epoch: 'Late Ordovician',
    color: '#008566',
  },
  {
    name: 'Sandbian',
    start: 453_000_000,
    end: 458_400_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Paleozoic',
    period: 'Ordovician',
    epoch: 'Late Ordovician',
    color: '#00785C',
  },
  {
    name: 'Late Ordovician',
    start: 443_800_000,
    end: 458_400_000,
    level: 'epoch',
    eon: 'Phanerozoic',
    era: 'Paleozoic',
    period: 'Ordovician',
    color: '#009270',
  },
  {
    name: 'Darriwilian',
    start: 458_400_000,
    end: 467_300_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Paleozoic',
    period: 'Ordovician',
    epoch: 'Middle Ordovician',
    color: '#006B52',
  },
  {
    name: 'Dapingian',
    start: 467_300_000,
    end: 470_000_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Paleozoic',
    period: 'Ordovician',
    epoch: 'Middle Ordovician',
    color: '#005E48',
  },
  {
    name: 'Middle Ordovician',
    start: 458_400_000,
    end: 470_000_000,
    level: 'epoch',
    eon: 'Phanerozoic',
    era: 'Paleozoic',
    period: 'Ordovician',
    color: '#006B52',
  },
  {
    name: 'Floian',
    start: 470_000_000,
    end: 477_700_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Paleozoic',
    period: 'Ordovician',
    epoch: 'Early Ordovician',
    color: '#00513E',
  },
  {
    name: 'Tremadocian',
    start: 477_700_000,
    end: 485_400_000,
    level: 'age',
    eon: 'Phanerozoic',
    era: 'Paleozoic',
    period: 'Ordovician',
    epoch: 'Early Ordovician',
    color: '#004434',
  },
  {
    name: 'Early Ordovician',
    start: 470_000_000,
    end: 485_400_000,
    level: 'epoch',
    eon: 'Phanerozoic',
    era: 'Paleozoic',
    period: 'Ordovician',
    color: '#00513E',
  },
  {
    name: 'Ordovician',
    start: 443_800_000,
    end: 485_400_000,
    level: 'period',
    eon: 'Phanerozoic',
    era: 'Paleozoic',
    color: '#009270',
  },
  {
    name: 'Furongian',
    start: 485_400_000,
    end: 497_000_000,
    level: 'epoch',
    eon: 'Phanerozoic',
    era: 'Paleozoic',
    period: 'Cambrian',
    color: '#8CAD56',
  },
  {
    name: 'Miaolingian',
    start: 497_000_000,
    end: 509_000_000,
    level: 'epoch',
    eon: 'Phanerozoic',
    era: 'Paleozoic',
    period: 'Cambrian',
    color: '#7FA049',
  },
  {
    name: 'Terreneuvian',
    start: 509_000_000,
    end: 541_000_000,
    level: 'epoch',
    eon: 'Phanerozoic',
    era: 'Paleozoic',
    period: 'Cambrian',
    color: '#72933C',
  },
  {
    name: 'Cambrian',
    start: 485_400_000,
    end: 541_000_000,
    level: 'period',
    eon: 'Phanerozoic',
    era: 'Paleozoic',
    color: '#7FA056',
  },
  {
    name: 'Paleozoic',
    start: 251_900_000,
    end: 541_000_000,
    level: 'era',
    eon: 'Phanerozoic',
    color: '#99C08D',
  },
  {
    name: 'Phanerozoic',
    start: 0,
    end: 541_000_000,
    level: 'eon',
    color: '#8DD9CC',
  },

  // ========== PROTEROZOIC EON ==========

  {
    name: 'Ediacaran',
    start: 541_000_000,
    end: 635_000_000,
    level: 'period',
    eon: 'Proterozoic',
    era: 'Neoproterozoic',
    color: '#FED96A',
  },
  {
    name: 'Cryogenian',
    start: 635_000_000,
    end: 720_000_000,
    level: 'period',
    eon: 'Proterozoic',
    era: 'Neoproterozoic',
    color: '#F9CA79',
  },
  {
    name: 'Tonian',
    start: 720_000_000,
    end: 1_000_000_000,
    level: 'period',
    eon: 'Proterozoic',
    era: 'Neoproterozoic',
    color: '#F4BB88',
  },
  {
    name: 'Neoproterozoic',
    start: 541_000_000,
    end: 1_000_000_000,
    level: 'era',
    eon: 'Proterozoic',
    color: '#FED96A',
  },
  {
    name: 'Stenian',
    start: 1_000_000_000,
    end: 1_200_000_000,
    level: 'period',
    eon: 'Proterozoic',
    era: 'Mesoproterozoic',
    color: '#F4AC97',
  },
  {
    name: 'Ectasian',
    start: 1_200_000_000,
    end: 1_400_000_000,
    level: 'period',
    eon: 'Proterozoic',
    era: 'Mesoproterozoic',
    color: '#EF9DA6',
  },
  {
    name: 'Calymmian',
    start: 1_400_000_000,
    end: 1_600_000_000,
    level: 'period',
    eon: 'Proterozoic',
    era: 'Mesoproterozoic',
    color: '#EA8EB5',
  },
  {
    name: 'Mesoproterozoic',
    start: 1_000_000_000,
    end: 1_600_000_000,
    level: 'era',
    eon: 'Proterozoic',
    color: '#F4AC97',
  },
  {
    name: 'Statherian',
    start: 1_600_000_000,
    end: 1_800_000_000,
    level: 'period',
    eon: 'Proterozoic',
    era: 'Paleoproterozoic',
    color: '#E57FC4',
  },
  {
    name: 'Orosirian',
    start: 1_800_000_000,
    end: 2_050_000_000,
    level: 'period',
    eon: 'Proterozoic',
    era: 'Paleoproterozoic',
    color: '#E070D3',
  },
  {
    name: 'Rhyacian',
    start: 2_050_000_000,
    end: 2_300_000_000,
    level: 'period',
    eon: 'Proterozoic',
    era: 'Paleoproterozoic',
    color: '#DB61E2',
  },
  {
    name: 'Siderian',
    start: 2_300_000_000,
    end: 2_500_000_000,
    level: 'period',
    eon: 'Proterozoic',
    era: 'Paleoproterozoic',
    color: '#D652F1',
  },
  {
    name: 'Paleoproterozoic',
    start: 1_600_000_000,
    end: 2_500_000_000,
    level: 'era',
    eon: 'Proterozoic',
    color: '#E57FC4',
  },
  {
    name: 'Proterozoic',
    start: 541_000_000,
    end: 2_500_000_000,
    level: 'eon',
    color: '#F74370',
  },

  // ========== ARCHEAN EON ==========

  {
    name: 'Neoarchean',
    start: 2_500_000_000,
    end: 2_800_000_000,
    level: 'era',
    eon: 'Archean',
    color: '#F0469E',
  },
  {
    name: 'Mesoarchean',
    start: 2_800_000_000,
    end: 3_200_000_000,
    level: 'era',
    eon: 'Archean',
    color: '#F0328A',
  },
  {
    name: 'Paleoarchean',
    start: 3_200_000_000,
    end: 3_600_000_000,
    level: 'era',
    eon: 'Archean',
    color: '#F01E76',
  },
  {
    name: 'Eoarchean',
    start: 3_600_000_000,
    end: 4_000_000_000,
    level: 'era',
    eon: 'Archean',
    color: '#F00A62',
  },
  {
    name: 'Archean',
    start: 2_500_000_000,
    end: 4_000_000_000,
    level: 'eon',
    color: '#F0469E',
  },

  // ========== HADEAN EON ==========

  {
    name: 'Hadean',
    start: 4_000_000_000,
    end: 4_600_000_000,
    level: 'eon',
    color: '#A91947',
  },
];

export function getPeriodAtTime(time: TimePoint): GeologicPeriod | null {
  const timeValue = getTimeValue(time);
  return (
    GEOLOGIC_PERIODS.find(
      period => timeValue >= period.start && timeValue < period.end
    ) ?? null
  );
}

export function getPeriodsInRange(
  startTime: TimePoint,
  endTime: TimePoint
): GeologicPeriod[] {
  const startValue = getTimeValue(startTime);
  const endValue = getTimeValue(endTime);
  return GEOLOGIC_PERIODS.filter(
    period => period.start < endValue && period.end > startValue
  );
}

export function getPeriodsByLevel(
  level: GeologicPeriod['level']
): GeologicPeriod[] {
  return GEOLOGIC_PERIODS.filter(period => period.level === level);
}

export function getEons(): GeologicPeriod[] {
  return getPeriodsByLevel('eon');
}

export function getEras(eon?: string): GeologicPeriod[] {
  const eras = getPeriodsByLevel('era');
  return eon ? eras.filter(era => era.eon === eon) : eras;
}

export function getPeriods(era?: string): GeologicPeriod[] {
  const periods = getPeriodsByLevel('period');
  return era ? periods.filter(period => period.era === era) : periods;
}

export function getEpochs(period?: string): GeologicPeriod[] {
  const epochs = getPeriodsByLevel('epoch');
  return period ? epochs.filter(epoch => epoch.period === period) : epochs;
}

export function getAges(epoch?: string): GeologicPeriod[] {
  const ages = getPeriodsByLevel('age');
  return epoch ? ages.filter(age => age.epoch === epoch) : ages;
}

export function formatTimeYearsAgo(years: number): string {
  if (years < 1_000) {
    return `${years.toLocaleString()} years ago`;
  } else if (years < 1_000_000) {
    return `${(years / 1_000).toFixed(1)}k years ago`;
  } else if (years < 1_000_000_000) {
    return `${(years / 1_000_000).toFixed(1)}M years ago`;
  } else {
    return `${(years / 1_000_000_000).toFixed(2)}B years ago`;
  }
}
